---
name: Pass Value Workflow
on:
  workflow_dispatch: null
jobs:
  build:
    name: Test run trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Setup Nodejs
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16"

      - name: Build application
        run: npm install

      - name: Install ts-node globally
        run: npm install -g ts-node

      - name: Generate Dummy String
        run: |
            ts-node src/helpers/StringGenerator.ts
        id: generate-dummy-string

      - name: Print the Dummy Value
        env:
          DUMMY_VALUE: ${{
            steps.generate-dummy-string.outputs.DUMMY_VALUE_CREATED_BY_TYPESCRIPT_CODE
            }}
        run: |
          echo  ${{ env.DUMMY_VALUE }}
