---
name: Curl Workflow
on:
  workflow_dispatch: null
jobs:
  build:
    name: Test run trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0

      - name: Execute cUrl Command
        run: |
            response=$(curl -X 'GET' 'https://petstore.swagger.io/v2/pet/1' -H 'accept: application/json')
            echo "response=$response" >> $GITHUB_ENV

      - name: Parse JSON Response
        run: |
            parsed_value=$(echo "${{ env.response }}" | jq -r '.id')
            echo "Parsed Value: $parsed_value"
